# Generated by Django 5.1 on 2024-08-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='activate',
            field=models.BooleanField(default=True),
        ),
    ]
