# Generated by Django 5.1 on 2024-08-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='menu_slider',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Menu Arkaplan Resmi'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slider',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='AnaSayfa Resmi'),
        ),
    ]
