# Generated by Django 5.1 on 2024-08-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_tenant_menu_slider_alter_tenant_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IyzicoSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=500, verbose_name='api_key')),
                ('secret_key', models.CharField(max_length=500, verbose_name='secret_key')),
                ('base_url', models.CharField(max_length=500, verbose_name='base_url')),
            ],
        ),
    ]
