# Generated by Django 5.1 on 2024-08-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_iyzicosetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='about',
            field=models.TextField(default=1, verbose_name='Hakkımızda'),
            preserve_default=False,
        ),
    ]
