# Generated by Django 5.1 on 2024-08-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_tenant_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToslaSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=500, verbose_name='api_key')),
                ('secret_key', models.CharField(max_length=500, verbose_name='secret_key')),
                ('base_url', models.CharField(max_length=500, verbose_name='base_url')),
                ('key_url', models.CharField(max_length=500, verbose_name='key_url')),
            ],
        ),
        migrations.DeleteModel(
            name='IyzicoSetting',
        ),
    ]
