# Generated by Django 5.1 on 2024-08-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_toslasetting_delete_iyzicosetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toslasetting',
            name='api_key',
            field=models.CharField(max_length=500, verbose_name='Api Pass'),
        ),
        migrations.AlterField(
            model_name='toslasetting',
            name='base_url',
            field=models.CharField(max_length=500, verbose_name='Api User'),
        ),
        migrations.AlterField(
            model_name='toslasetting',
            name='key_url',
            field=models.CharField(max_length=500, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='toslasetting',
            name='secret_key',
            field=models.CharField(max_length=500, verbose_name='Base URL'),
        ),
    ]
