# Generated by Django 5.1 on 2024-08-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='Açıklama Yok', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('waiting', 'Müşteri Teslim Alması Bekleniyor'), ('delivered', 'Teslim Edildi')], default='pending', max_length=20, verbose_name='Durum'),
        ),
    ]
